obj-$(CONFIG_HC_XPT2046) += xpt2046/
obj-$(CONFIG_HC_HY46XX) += hy46xx/
obj-$(CONFIG_HC_ILITEK) += ilitek_v5912/
obj-$(CONFIG_HC_GT911) += gt911/
obj-$(CONFIG_HC_BLT1680) += blt1680/
obj-$(CONFIG_HC_SIS9509) += sis9509/
obj-$(CONFIG_HC_FT5426) += ft5426/
obj-$(CONFIG_HC_HYNITRON_CST8XXX) += hynitron_cst8xxx/
