libuvc-y := ctrl-gen.o \
			ctrl.o \
			device.o \
			diag.o \
			frame-mjpeg.o \
			frame.o \
			init.o \
			misc.o \
			stream.o
			# example.o 

cflags-y += -Wno-format
obj-y += libuvc.o
