#ifndef _STRING_ID_
#define _STRING_ID_

#define STR_QR_CONNECT_AP    1
#define STR_QR_SCAN_WIFI     2
#define STR_QR_CONFIG        3
#define STR_WIFI_SCANNING    4
#define STR_WIFI_CONNECTING  5
#define STR_MIRA_CONNECTING  6
#define STR_MIRA_CONNECT_OK  7
#define STR_MIRA_GOT_IP_OK   8
#define STR_AIR_PLAY_MUSIC   9
#define STR_INSERT_ANDROID_OR_APPLE 10
#define STR_REINSERT_ANDROID_OR_APPLE 11
#define STR_PICTURE_MODE     12
#define STR_CONSTRAST        13
#define STR_HUE              14
#define STR_BRIGHTNESS       15
#define STR_COLOR            16
#define STR_SHARPNESS        17
#define STR_COLOR_TEMP       18
#define STR_SOUND_MODE       19
#define STR_TREBLE           20
#define STR_BASS             21
#define STR_BALANCE          22
#define STR_BT_SETTING       23
#define STR_SEARCH_BT        24
#define STR_BT_DEVICE        25
#define STR_BT_MY_DEV        26
#define STR_BT_OTHER_DEV     27
#define STR_NO_BT            28
#define STR_BT_CONN          29
#define STR_BT_DISCONN       30
#define STR_BT_SAVED         31
#define STR_BT_MAKE_DISCONN  32
#define STR_BT_MAKE_CONN     33
#define STR_WIFI_CONNING     34
#define STR_WIFI_SEARCHING   35
#define STR_WIFI_DEVICE_ABNORMAL 36
#define STR_WIFI_PWD_NULL    37
#define STR_WIFI_CONN_SUCCESS 38
#define STR_WIFI_CONN_FAILED 39
#define STR_WIFI_RE_ENTER_PWD 40
#define STR_PROMPT_YES       41
#define STR_PROMPT_NO        42
#define STR_ENTER_WORD       43
#define STR_WIFI_SSID_NULL   44
#define STR_WIFI_SSID_TOO_LONG 45
#define STR_WIFI_CANCEL      46
#define STR_BT_DELETE        47
#define STR_OSD_LANG_TITLE   48
#define STR_OSD_LANG         49
#define STR_FLIP             50
#define STR_ASPECT_RATIO     51
#define STR_RESTORE_FACTORY_DEFAULT 52
#define STR_UPGRADE          53
#define STR_UPGRADE_NOT_POWER_OFF 54
#define STR_UPGRADE_DOWNLOADING 55
#define STR_UPGRADEING       56
#define STR_AUTO_SLEEP       57
#define STR_OSD_TIMER        58
#define STR_UPGRADE_NO_DEV   59
#define STR_UPGRADE_NO_SOFTWATE 60
#define STR_UPGRADE_LOAD_ERR 61
#define STR_UPGRADE_CRC_ERR  62
#define STR_UPGRADE_VERSION_ERR 63
#define STR_UPGRADE_PRODUCT_ERR 64
#define STR_UPGRADE_DECO_ERR 65
#define STR_UPGRADE_ERR      66
#define STR_UPGRADE_SUCCESS_MSG1 67
#define STR_UPGRADE_SUCCESS_MSG2 68
#define STR_KEYSTONE         69
#define STR_VERSION_INFO     70
#define STR_PICTURE_MODE_TITLE 71
#define STR_SOUND_MODE_TITLE 72
#define STR_OPTION_MODE_TITLE 73
#define STR_ADJUST_MODE_TITLE 74
#define STR_FOOT_SURE        75
#define STR_FOOT_MENU        76
#define STR_FOOT_MOVE        77
#define STR_FOOT_OFF         78
#define STR_MOVIE            79
#define STR_MUSIC            80
#define STR_PHOTO            81
#define STR_TEXT             82
#define STR_BACK             83
#define STR_PLAY             84
#define STR_PAUSE            85
#define STR_STOP             86
#define STR_FF               87
#define STR_FB               88
#define STR_MUSIC_NEXT       89
#define STR_MUSIC_PREV       90
#define STR_ROUND            91
#define STR_LISTROUND        92
#define STR_SINGLEROUND      93
#define STR_ZOOMIN           94
#define STR_ZOOMOUT          95
#define STR_ROTATE_LEFT      96
#define STR_ROTATE_RIGHT_K   97
#define STR_NO_EFFECT        98
#define STR_NOR_EFFECT       99
#define STR_SHUTTER_EFFECT   100
#define STR_BRUSH_EFFECT     101
#define STR_SLIDE_EFFECT     102
#define STR_RAND_EFFECT      103
#define STR_FADE_EFFECT      104
#define STR_FILE_FAIL        105
#define STR_AUDIO_USPT       106
#define STR_VIDEO_USPT       107
#define STR_USPT_VIDEO_TYPE  108
#define STR_USPT_AUDIO_TYPE  109
#define STR_AUDIO_ERROR      110
#define STR_VIDEO_ERROR      111
#define STR_PIC_ERROR        112
#define STR_HDMI_TITLE1      113
#define STR_HDMI_TITLE2      114
#define STR_HDMI_TITLE       115
#define STR_MEDIA_TITLE      116
#define STR_AV_TITLE         117
#define STR_HOME_TITLE       118
#define STR_SETTING_TITLE    119
#define STR_IPTV_YTB         120
#define STR_CHANNEL_TITLE    121
#define STR_WIFI_TITLE       122
#define STR_WIRED_TITLE      123
#define STR_WIRELESS_TITLE   124
#define STR_OFF              125
#define STR_ON               126
#define STR_STANDARD         127
#define STR_DYNAMIC          128
#define STR_MILD             129
#define STR_USER             130
#define STR_COLD             131
#define STR_WARM             132
#define STR_SPORTS           133
#define STR_ENGLISH          134
#define STR_CHINESE          135
#define STR_FRONT_TABLE      136
#define STR_FRONT_CEILING    137
#define STR_BACK_TABLE       138
#define STR_BACK_CEILING     139
#define STR_RESTORE_OK_1     140
#define STR_RESTORE_OK_2     141
#define STR_RESTORE_CLOSE    142
#define STR_OSD_TIME_5S      143
#define STR_OSD_TIEM_10S     144
#define STR_OSD_TIME_15S     145
#define STR_OSD_TIME_20S     146
#define STR_OSD_TIME_25S     147
#define STR_OSD_TIME_30S     148
#define STR_AUTO_SLEEP_1H    149
#define STR_AUTO_SLEEP_2H    150
#define STR_AUTO_SLEEP_3H    151
#define STR_INPUT_SOURCE     152
#define STR_VOLUME           153
#define STR_LIST             154
#define STR_INFO             155
#define STR_SF               156
#define STR_STEP             157
#define STR_INFO_RES         158
#define STR_INFO_FRAME       159
#define STR_INFO_AUDIO       160
#define STR_INFO_SUBTITLE    161
#define STR_INFO_SIZE        162
#define STR_INFO_ALBUM       163
#define STR_INFO_ARTIST      164
#define STR_INFO_BIT         165
#define STR_INFO_EXIT        166
#define STR_PANEL_CLOSE      167
#define STR_MUTE             168
#define STR_MUSIC_OFF        169
#define STR_MUSIC_ON         170
#define STR_MUSIC_SRC        171
#define STR_FILE_DATE        172
#define STR_FILE_TIME        173
#define STR_SETUP            174
#define STR_ASPECT_AUTO      175
#define STR_ASPECT_4_3       176
#define STR_ASPECT_16_9      177
#define STR_USB_MOUNT_FAIL_MSG 178
#define STR_NETWORK_ERR      179
#define STR_CONNECT_WIFI_FAIL 180
#define STR_CONNECT_WIFI_FIRST 181
#define STR_VIDEO_DATA_ERR   182
#define STR_AUDIO_DATA_ERR   183
#define STR_VIDEO_FORMAT_NOT_SUPPORT 184
#define STR_AUDIO_FORMAT_NOT_SUPPORT 185
#define STR_WIFI_DISCONNECT  186
#define STR_MEDIA_CONTAINER_NOT_SUPPORT 187
#define STR_WIFI_SAVED       188
#define STR_WIFI_NEARBY      189
#define STR_WIFI_SEARCH      190
#define STR_WIFI_ADD         191
#define STR_WIFI_RET         192
#define STR_WIFI_STRENGTH    193
#define STR_WIFI_SECURITY    194
#define STR_WIFI_PWD         195
#define STR_WIFI_SHOW_PWD    196
#define STR_WIFI_NET_MODE    197
#define STR_WIFI_IP_ADDR     198
#define STR_WIFI_NET_MASK    199
#define STR_WIFI_GATE_WAY    200
#define STR_WIFI_DNS         201
#define STR_WIFI_MAC         202
#define STR_WIFI_STATIC_IP   203
#define STR_WIFI_CONNECT_ERR 204
#define STR_WIFI_NOT_CONNECT 205
#define STR_RESET            206
#define STR_FOCUS_FORWAD     207
#define STR_FOCUS_BACK       208
#define STR_FOCUS            209
#define STR_EBOOK_UP         210
#define STR_EBOOK_DOWN       211
#define STR_EBOOK_PREV       212
#define STR_EBOOK_NEXT       213
#define STR_SUBTITLE_MSG     214
#define STR_ZOOMMOVE         215
#define STR_MP_NO_DEV        216
#define STR_MIRROR_ROTATE_ON 217
#define STR_MIRROR_ROTATE_OFF 218
#define STR_FRENCH           219
#define STR_LANG             220
#define STR_ENTER_STANDBY    221
#define STR_WINDOW_SCALE     222
#define STR_WIFI_NOT_READY   223
#define STR_ANDROID_SCAN_QR  224
#define STR_USB_UPG_READ     225
#define STR_NET_UPG_DOWNLOAD 226
#define STR_USB_UPG_OPEN_FILE_FAIL 227
#define STR_USB_UPG_FILE_LARGE 228
#define STR_USB_UPG_READ_FAIL 229
#define STR_NET_UPG_HTTP_BAD 230
#define STR_UPG_USER_CANCEL  231
#define STR_UPG_PRODUCT_ID_MISMATCH 232
#define STR_UPG_SW_VER_NOT_UPG 233
#define STR_UPG_SW_ILLGAL    234
#define STR_UPG_UNZIP_FAIL   235
#define STR_UPG_BURNING      236
#define STR_USB_UPG_OK       237
#define STR_NET_UPG_OK       238
#define STR_UPG_BURN_FAIL    239
#define STR_BT_DISCONNECTED  240
#define STR_BT_CONNECTED     241
#define STR_BT_CONN_FAILED   242
#define STR_HDMI_FORMAT_USPT 243
#define STR_NO_SIGNAL        244
#define STR_VIDEO_LINK_ERR   245
#define STR_VIDEO_LINK_ERR_PLAY_NEXT 246
#define STR_VIDEO_LINK_ERR_PLAY_PREV 247
#define STR_VIDEO_PLAY_FAIL  248
#define STR_FIRST_VIDEO      249
#define STR_LAST_VIDEO       250
#define STR_VIDEO_PLAY_FAIL_PLAY_NEXT 251
#define STR_WIFI_PLUGOUT_REBOOT 252
#define STR_VIDEO_INFO_ERR_RETRY 253
#define STR_VIDEO_INFO_ERR_RETRY_AGAIN 254
#define STR_PREVIEW_ERROR    255
#define STR_IMG_DIS_REALSIZE 256
#define STR_IMG_DIS_THUMBNAIL 257
#define STR_IMG_DIS_AUTO     258
#define STR_IMG_DIS_CROP     259
#define STR_IMG_DIS_FULLSCREEN 260
#define STR_UPGRADE_PROMPT   261
#define STR_SOUND_EQ         262
#define STR_IUSB_NO_DATA     263
#define STR_USB_READ_ERROR   264
#define STR_FULL_COLOR_DIS   265
#define STR_IMAGE_SET        266
#define STR_ENABLE_PQ        267
#define STR_DYNAMIC_CTR      268
#define STR_HW_INFO          269
#define STR_FACTORY_SETTING  270
#define STR_CVBS_AFE         271
#define STR_LOW_BATTERY      272
#define STR_BATTERY_SHUTDOWN 273
#define STR_WIFI_DEV_DETECTING 274
#define STR_WIFI_DEV_DETECT_FAIL 275
#define STR_WIFI_DEV_DETECT_OK 276
#define STR_LIMITED          277
#define STR_VIDEO_DELAY      278
#define STR_MOSAIC_EFFECT    279
#define STR_SOUND_OUTPUT_MODE 280
#define STR_SOUND_OUTPUT_SPDFI 281
#define STR_SOUND_DIGITAL_OUTPUT 282
#define STR_SOUND_RAW        283
#define STR_SOUND_PCM        284
#define STR_SOUND_SPEAKER    285
#define STR_VIDEO_NEXT       286
#define STR_VIDEO_PREV       287
#define STR_PHOTO_NEXT       288
#define STR_PHOTO_PREV       289
#define STR_EQ_NORMAL        290
#define STR_EQ_ROCK          291
#define STR_EQ_POP           292
#define STR_EQ_JAZZ          293
#define STR_EQ_CLASSIC       294
#define STR_EQ_VOCAL         295
#define STR_EQ_CUSTOME       296
#define STR_EQ_OPEN_MSG      297
#define STR_EQ_CLOSE_MSG     298
#define STR_MP_UI_ERR        299
#define STR_MP_UI_ERR_RETRY  300
#define STR_BT_SPEAKER_SET   301
#define STR_BT_SPEAKER_NAME  302
#define STR_BT_SPEAKER_MODE  303
#define STR_INPUT_NEW_BTNAME 304
#define STR_CVBS_TRAINING    305
#define STR_CVBS_IN_GAIN     306
#define STR_CVBS_RUNNING     307
#define STR_CVBS_TRAINING_OK 308
#define STR_CVBS_RUNNING_FAILED 309
#define STR_EXIT_MP_FIRST    310
#define STR_EXIT_HDMI_RX_FIRST 311
#define STR_MULTI_OS         312
#define STR_REGION           313
#define STR_REGION_US        314
#define STR_REGION_HK        315
#define STR_REGION_TW        316
#define STR_REGION_JP        317
#define STR_QUALITY          318
#define STR_SEARCH_SOET_BY   319
#define STR_RELEVANCE        320
#define STR_UPLOAD_DATE      321
#define STR_VIEW_COUNT       322
#define STR_RATING           323
#define STR_TITLE            324
#define STR_FOOT_PAGE        325
#define STR_AIRP2P           326
#define STR_NET_UPG          327
#define STR_USB_UPG          328
#define STR_CONFIG_ERROR     329
#define STR_NO_HISTORY       330
#define STR_WIFI_NOT_CONNECTING 331
#define STR_AIRP2P_CH        332
#define STR_AIRP2P_CH_6      333
#define STR_AIRP2P_CH_44     334
#define STR_AIRP2P_CH_48     335
#define STR_AIRP2P_CH_149    336
#define STR_NET_UPG_REQUEST  337
#define STR_BACKLIGHT        338
#define STR_TRADITIONAL_CHINESE 339
#define STR_GERMAN           340
#define STR_SPANISH          341
#define STR_PORTUGUESE       342
#define STR_ITALIAN          343
#define STR_POLISH           344
#define STR_SWEDISH          345
#define STR_FINNISH          346
#define STR_GREEK            347
#define STR_DANISH           348
#define STR_NORWEGIAN        349
#define STR_HUNGARIAN        350
#define STR_HEBREW           351
#define STR_RUSSIAN          352
#define STR_VIETNAMESE       353
#define STR_THAI             354
#define STR_ARABIC           355
#define STR_JAPANESE         356
#define STR_KOREAN           357
#define STR_INDONESIAN       358
#define STR_NETHERLANDS      359
#define STR_TURKEY           360
#define STR_VERTICAL_KEYSTONE 361
#define STR_TRAPEZOIDAL_RESET 362
#define STR_ZOOM_SCREEN_RESET 363
#define STR_AUTO_SLEEP_15M   364
#define STR_AUTO_SLEEP_30M   365
#define STR_AUTO_SLEEP_POWER_TIMER 366
#define STR_MP_TEXT          367
#define STR_ATKEYSTONE       368
#define STR_ATK_OUTOF        369
#define STR_OVER_TEMP        370
#define STR_BR_MODE          371
#define STR_HCC              372
#define STR_HCC_LABEL1       373
#define STR_HCC_LABEL2       374
#define STR_HCC_LABEL3       375
#define STR_HCC_PROMPT0      376
#define STR_HCC_PROMPT1      377
#define STR_HC               378
#define STR_HCC_LABEL        379
#define STR_HCC_LABEL4       380

#endif//_STRING_ID_
