cflags-y += -Wno-sign-compare
cflags-y += -L$(STAGING_DIR)/usr/lib/ -lusb -luvc

libuvc-example-y += usb_libuvc_demo.o
libuvc-example-y += usb_libuvc_demo2.o
libuvc-example-y += usb_libuvc_demo3.o
libuvc-example-y += usb_libuvc_demo4.o

obj-y += libuvc-example.o
