#ifndef __HCRTOS_KERNEL_DYNLOAD_H
#define __HCRTOS_KERNEL_DYNLOAD_H

#ifdef __cplusplus
 extern "C" {
#endif

typedef enum DYNLOAD_SECTION_ID {
	DYNLOAD_SECTION_ID_NONE,
	DYNLOAD_SECTION_ID_MP3,
	DYNLOAD_SECTION_ID_AAC,
	DYNLOAD_SECTION_ID_AACELD,
	DYNLOAD_SECTION_ID_AC3,
	DYNLOAD_SECTION_ID_EAC3,
	DYNLOAD_SECTION_ID_PCM,
	DYNLOAD_SECTION_ID_FLAC,
	DYNLOAD_SECTION_ID_VORBIS,
	DYNLOAD_SECTION_ID_WMA,
	DYNLOAD_SECTION_ID_WMAPRO,
	DYNLOAD_SECTION_ID_OPUS,
	DYNLOAD_SECTION_ID_RA,
	DYNLOAD_SECTION_ID_APE,
	DYNLOAD_SECTION_ID_PCMDVD,
	DYNLOAD_SECTION_ID_ALAC,
	DYNLOAD_SECTION_ID_MPEG2,
	DYNLOAD_SECTION_ID_MPEG4,
	DYNLOAD_SECTION_ID_IMAGE,
	DYNLOAD_SECTION_ID_H264,
	DYNLOAD_SECTION_ID_RV,
	DYNLOAD_SECTION_ID_VC1,
	DYNLOAD_SECTION_ID_VP8,
	DYNLOAD_SECTION_ID_MEDIAPLAYER,
	DYNLOAD_SECTION_ID_RTL8188FU,
	DYNLOAD_SECTION_ID_RTL8188EU,
	DYNLOAD_SECTION_ID_RTL8723AS,
	DYNLOAD_SECTION_ID_RTL8723BS,
	DYNLOAD_SECTION_ID_RTL8733BU,
	DYNLOAD_SECTION_ID_RTL8811CU,
	DYNLOAD_SECTION_ID_RTL8822CS,
	DYNLOAD_SECTION_ID_MAX,
} dynload_section_id_e;

int dynload_builtin_section(enum DYNLOAD_SECTION_ID id);

#ifdef __cplusplus
}
#endif

#endif
