EXTRA_CFLAGS = -Werror=unused-variable -Werror=unused-parameter
hccast_test-y = hccast_test_com.o
hccast_test-$(BR2_PACKAGE_HCCAST_WIFI_CAST_EXAMPLES) += wifi_cast_test.o 
hccast_test-$(BR2_PACKAGE_HCCAST_USB_CAST_EXAMPLES) += usb_cast_test.o 
obj-y += hccast_test.o
