################################################################################
#
# hctinyplayer-registry
#
################################################################################

HCTINYPLAYER_REGISTRY_SITE_METHOD = UNDEFINED
HCTINYPLAYER_REGISTRY_SITE = UNDEFINED
HCTINYPLAYER_REGISTRY_LICENSE = LGPL-2.0+
HCTINYPLAYER_REGISTRY_LICENSE_FILES = COPYING
HCTINYPLAYER_REGISTRY_INSTALL_STAGING = YES

HCTINYPLAYER_REGISTRY_BUILD_CMDS = rsync -au --chmod=u=rwX,go=rX  --exclude .svn --exclude .git --exclude .hg --exclude .bzr --exclude CVS $(TOPDIR)/components/hctinyplayer-registry/source/ $(@D)
HCTINYPLAYER_REGISTRY_EXTRACT_CMDS = rsync -au --chmod=u=rwX,go=rX  --exclude .svn --exclude .git --exclude .hg --exclude .bzr --exclude CVS $(TOPDIR)/components/hctinyplayer-registry/source/ $(@D)

HCTINYPLAYER_REGISTRY_CONF_OPTS += -DHCRTOS=ON

ifeq ($(BR2_PACKAGE_HCTINYPLAYER_TEST),y)
	HCTINYPLAYER_REGISTRY_CONF_OPTS += -DBR2_PACKAGE_HCTINYPLAYER_TEST=ON
	HCTINYPLAYER_REGISTRY_DEPENDENCIES += pthread
endif

ifeq ($(BR2_PACKAGE_HCTINYPLAYER_PROTOCOL_FILE),y)
	HCTINYPLAYER_REGISTRY_CONF_OPTS += -DBR2_PACKAGE_HCTINYPLAYER_PROTOCOL_FILE=ON
endif

ifeq ($(BR2_PACKAGE_HCTINYPLAYER_DEMUXER_FLV),y)
	HCTINYPLAYER_REGISTRY_CONF_OPTS += -DBR2_PACKAGE_HCTINYPLAYER_DEMUXER_FLV=ON
endif

ifeq ($(BR2_PACKAGE_HCTINYPLAYER_DEMUXER_MJPEG),y)
	HCTINYPLAYER_REGISTRY_CONF_OPTS += -DBR2_PACKAGE_HCTINYPLAYER_DEMUXER_MJPEG=ON
endif

ifeq ($(BR2_PACKAGE_HCTINYPLAYER_PARSER_MPEGAUDIO),y)
	HCTINYPLAYER_REGISTRY_CONF_OPTS += -DBR2_PACKAGE_HCTINYPLAYER_PARSER_MPEGAUDIO=ON
endif

ifeq ($(BR2_PACKAGE_HCTINYPLAYER_PARSER_H264),y)
	HCTINYPLAYER_REGISTRY_CONF_OPTS += -DBR2_PACKAGE_HCTINYPLAYER_PARSER_H264=ON
endif

$(eval $(cmake-package))
