cflags-y += -Wno-error=format=
spi-y += spidev_test.o
spi-$(CONFIG_CMDS_FLASH_TEST) += mtd_test.o
spi-$(CONFIG_CMDS_FLASH_TORTURETEST) += torturetest.o
spi-$(CONFIG_CMDS_FLASH_LOCK_SAMPLE) += flash_lock.o
obj-y += spi.o
