#ifndef __UAPI_NDS03_H
#define __UAPI_NDS03_H
#include <hcuapi/iocbase.h>
#define INPUT_NDS03_IOCBASE 100

#define NDS03_SET_WORK_MODE					_IO (INPUT_NDS03_IOCBASE, 0)
#define NDS03_SET_CALIBRATION_DISTANCE		_IO (INPUT_NDS03_IOCBASE, 1)
#define NDS03_START				_IO (INPUT_NDS03_IOCBASE, 3)
#define NDS03_STOP				_IO (INPUT_NDS03_IOCBASE, 4)

typedef enum NDS03_WORK_MODE_E {
	NDS03_WORK_SINGINGRANGING = 0,
	NDS03_WORK_CONTIUNOUSRANGING,
	NDS03_WORK_CALIBRATION,
} nds03_wrok_mode_e;

#endif
