
# Linux driver folder

#obj-y	+= hynitron_i2c.o
#obj-y	+= hynitron_esd_check.o
#obj-y	+= hynitron_tool_debug.o
#obj-y	+= hynitron_update_firmware.o
#obj - y += hynitron_gesture.o
#obj-y	+= hynitron_proximity.o

__hynitron-y += hynitron_core.o hynitron_i2c.o hynitron_update_firmware.o
obj-y	+= __hynitron.o
