input_event-y += input_test.o
input_event-$(CONFIG_CMDS_INPUT_POLL_TEST) += input_poll_test.o
input_event-$(CONFIG_CMDS_INPUT_JOYSTICK_TEST) += joystick_test.o
input_event-$(CONFIG_CMDS_INPUT_IOCTL_TEST) += input_ioctl.o

obj-y += input_event.o
